### ISSUE TITLE
[Question] Since pythonw.exe is used, is pyinstaller compatible? (on Windows OS of course)

### ISSUE THREAD

**Issue by mo-han** [Muterra/py_daemoniker#14]
on windows, app packaged by pyinstaller is launched from a custom .exe file.
since there is neither python.exe nor pythonw.exe, would daemoniker still work?

---

```
# this can create a subprocess without console intrinsically
subprocess.Popen(creationflags=DETACHED_PROCESS | subprocess.CREATE_NEW_PROCESS_GROUP)
# maybe this could replace the pythonw.exe solution?
```

**Comment by Badg** [comment]
This isn't tested with pyinstaller, so I don't know for sure, but I doubt it. To be completely honest, the project is approximately unmaintained. Approximating a unix double-fork within windows was really very finicky and involved a lot of manual testing on my part to make sure that the process survived closing the launching window; I really don't have the bandwidth to add or test compatibility with pyinstaller.

I can sympathize with wanting a simple way to create a windows background service; it's a bit of a pain, and that was a big part of why I wrote this in the first place. But for what it's worth, if you're going to the effort of distributing a standalone executable via pyinstaller, you should probably be doing a proper windows service. The approach taken here for windows is pretty hacky (read: not really production-grade), and to be honest even in the unix world, the double-fork strategy has fallen way out of favor compared with a proper service manager (for example, systemd).
